---
- name: Get existing API tokens
  ansible.builtin.uri:
    url: "{{ panel_url }}/api/tokens"
    method: GET
    headers:
      Origin: "{{ panel_url }}"
      Authorization: "Bearer {{ auth_token }}"
      X-Remnawave-Client-Type: "browser"
    status_code: 200
  register: tokens_response

- name: Set API token fact
  ansible.builtin.set_fact:
    remnawave_api_token: "{{ (tokens_response.json.response.apiKeys | first).token }}"
  when: tokens_response.json.response.apiKeys | length > 0

- name: Write PANEL_API_TOKEN to local .env
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/../../.env"
    regexp: "^PANEL_API_TOKEN="
    line: "PANEL_API_TOKEN='{{ remnawave_api_token }}'"
    create: true
  delegate_to: localhost
  become: false
  when: remnawave_api_token is defined

# Set the default API token to Krisa bot if the token is empty.
- name: Check if KRISA_BOT_REMNAWAVE_API_TOKEN is set
  command: grep -E "^KRISA_BOT_REMNAWAVE_API_TOKEN=['\"]?[a-zA-Z0-9]" "{{ playbook_dir }}/../../.env"
  delegate_to: localhost
  become: false
  register: krisa_token_check
  failed_when: false
  changed_when: false

- name: Write KRISA_BOT_REMNAWAVE_API_TOKEN to local .env
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/../../.env"
    regexp: "^KRISA_BOT_REMNAWAVE_API_TOKEN="
    line: "KRISA_BOT_REMNAWAVE_API_TOKEN='{{ remnawave_api_token }}'"
    create: true
  delegate_to: localhost
  become: false
  when: remnawave_api_token is defined and krisa_token_check.rc != 0
