---
- name: Setup Backups
  hosts: remnawave_panel
  become: true

  vars:
    # Default to false if not provided
    krisa_bot_backup: "{{ krisa_bot_backup | default(false) | bool }}"

  tasks:
    - name: Run Backup Role
      include_role:
        name: backup
