---
- name: Destroy Bot
  hosts: remnawave_panel
  become: true

  tasks:
    - name: Tear down Krisa Bot Stack
      community.docker.docker_compose_v2:
        project_src: /opt/krisa-bot
        state: absent
      ignore_errors: true

    - name: Remove remnawave docker-compose.override.yml
      file:
        path: /opt/remnawave/docker-compose.override.yml
        state: absent

    - name: Remove Bot Caddy Configuration
      file:
        path: /opt/remnawave/caddy/site-confs/bot.caddy
        state: absent

    - name: Reload Caddy
      community.docker.docker_container_exec:
        container: caddy
        command: caddy reload --config /etc/caddy/Caddyfile
      ignore_errors: true

    - name: Update Remnawave Panel Configuration
      community.docker.docker_compose_v2:
        project_src: /opt/remnawave
        state: present
        pull: never

    - name: Remove Krisa Bot directory
      file:
        path: /opt/krisa-bot
        state: absent
