---
- name: Wait for Connectivity
  hosts: remna_nodes
  gather_facts: false
  tasks:
    - name: Wait for SSH to be available
      ansible.builtin.wait_for_connection:
        delay: 0
        timeout: 180
        connect_timeout: 2
        sleep: 1

- name: Configure VPN Nodes
  hosts: remna_nodes
  become: true

  vars_files:
    - "../../config/panel.yaml"
    - "../../config/nodes.yaml"

  # Global Variables
  vars:
    panel_ip: "{{ server.panel_ip }}"
    node_port: "{{ settings.node_port }}"
    docker_arch_map:
      x86_64: amd64
      aarch64: arm64
    docker_users:
      - "{{ ansible_user }}"
      - "{{ settings.admin.username }}"

  roles:
    - role: ufw
      vars:
        ufw_open_ports: [80, 443, 8443]
    - docker
    - remna_node/setup
    - remna_node/logrotate
    - node_exporter
    - reboot
