---
- name: Wait for Connectivity
  hosts: remna_panel
  gather_facts: false
  tasks:
    - name: Wait for SSH to be available
      ansible.builtin.wait_for_connection:
        delay: 0
        timeout: 180
        connect_timeout: 2
        sleep: 1

- name: Deploy Remnawave Panel from Backup
  hosts: remna_panel
  become: true

  vars_files:
    - "../../config/panel.yaml"

  vars:
    docker_arch_map:
      x86_64: amd64
      aarch64: arm64
    docker_users:
      - "{{ ansible_user }}"
      - "{{ server.admin.username }}"

    # Derived variables
    panel_domain: "{{ domain.panel_subdomain }}.{{ domain.zone }}"
    panel_url: "https://{{ panel_domain }}"
    subpage_domain: "{{ domain.sub_subdomain }}.{{ domain.zone }}"

  roles:
    - role: ufw
      vars:
        ufw_open_ports: [80, 443]
    - docker
    - remna_panel/setup
    - backup
    - remna_panel/caddy
    # Uploads backup, runs restore, retrieves api token, config profile uuid, active inbounds, panel cert.
    - remna_panel/restore
    - role: remna_panel/subpage
      when: domain.sub_subdomain | default('') | length > 0
    - reboot
