---
- name: Get Admin Username
  ansible.builtin.set_fact:
    admin_username: "{{ server.admin.username }}"

- name: Get admin user info
  ansible.builtin.getent:
    database: passwd
    key: "{{ admin_username }}"

- name: Set admin user facts
  ansible.builtin.set_fact:
    admin_uid: "{{ ansible_facts.getent_passwd[admin_username][1] }}"
    admin_gid: "{{ ansible_facts.getent_passwd[admin_username][2] }}"

- name: Ensure Krisa Bot directory exists
  file:
    path: /opt/krisa-bot
    state: directory
    mode: "0755"
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"

- name: Create .env file
  template:
    src: krisa_bot.env.j2
    dest: /opt/krisa-bot/.env
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: "0600"

- name: Create docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /opt/krisa-bot/docker-compose.yml
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: "0644"

- name: Ensure logs directory exists
  file:
    path: /opt/krisa-bot/data/logs
    state: directory
    mode: "0755"
    owner: "1000"
    group: "1000"

- name: Create remnawave docker-compose.override.yml
  template:
    src: panel_docker-compose.override.yml.j2
    dest: /opt/remnawave/docker-compose.override.yml
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: "0644"

- name: Update Remnawave Panel Configuration
  community.docker.docker_compose_v2:
    project_src: /opt/remnawave
    state: present
    pull: never

- name: Deploy Bot Caddy Configuration
  template:
    src: bot_caddy.j2
    dest: /opt/remnawave/caddy/site-confs/bot.caddy
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: "0644"

- name: Reload Caddy
  community.docker.docker_container_exec:
    container: caddy
    command: caddy reload --config /etc/caddy/Caddyfile
  ignore_errors: true

- name: Start Krisa Bot Stack
  community.docker.docker_compose_v2:
    project_src: /opt/krisa-bot
    state: present
    wait: true
    wait_timeout: 60
    pull: always
