services:
  krisa-bot:
    image: ghcr.io/yarosazonov/krisa-remna-tg-bot:0.1
    container_name: krisa-bot
    hostname: krisa-bot
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    extra_hosts:
      # we need to go through caddy to bypass panel's X headers check
      # so we set to resolve panel domain to host gateway to route traffic locally
      - "${REMNAWAVE_PANEL_DOMAIN}:host-gateway"
    env_file:
      - .env
    volumes:
      - bot-db:/app/data/db
      - ./data/logs:/app/data/logs
    networks:
      - remnawave-network
    restart: unless-stopped

volumes:
  bot-db:
    driver: local

networks:
  remnawave-network:
    external: true
